config/routes.rb
Rails.application.routes.draw do
  slug = %r{[a-z0-9\-]+/[a-z0-9\-_]+}i

  authenticated :user do
    root to: 'boards#index', as: :authenticated_root
  end

  root to: 'pages#index'

  authenticate :user do
    mount Flipper::UI.app(Flipper), at: '/__flipper__'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resource :user, only: [] do
    resources :features, param: :name, only: %i[destroy] do
      post :create, on: :member
    end
  end

  resources :ideas do
    post :update_multiple, on: :collection
  end

  resources :boards do
    resources :board_tickets, as: :tickets, only: %i[show create] do
      resources :moves, controller: :ticket_moves, only: :create
      resource :labelling, path: 'labels', only: :update
      resource :assignment, path: 'assignees', controller: 'ticket_assignments', only: :update
    end
    get 'tickets/:slug/:number' => 'board_tickets#show', as: :slugged_ticket, constraints: {
      slug: slug
    }
    resources :next_actions, only: :index

    resources :kpis, only: :index
    resource :cumulative_flow, only: :show, controller: 'cumulative_flow'

    # This needs to be last to avoid it intercepting the routes above
    get '*extras' => :show, as: :client_side, on: :member, constraints: { format: :html }
  end

  resources :swimlanes, only: [] do
    resources :tickets, controller: :board_tickets, only: :index
  end

  resources :repos, only: [] do
    resources :labels, only: :index
    resources :assignees, only: :index
  end

  namespace :webhook, only: :create, format: :json do
    resource :github, controller: 'github'
    resource :opsworks
  end

  get '/gh_assets/:slug/*path' => 'github_assets#show', as: :github_asset, constraints: { slug: slug }

  namespace :api do
    resources :boards, only: :show do
      resources :board_tickets, only: %i[index]
      resources :releases, only: :create
    end
  end

  get '/__components__(/*extras)' => 'components#index', as: :components if Rails.env.development?
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :submitter, class_name: 'User'
  before_create :set_default_position
  after_create_commit -> { broadcast_append_to "ideas" }

  enum status: { pending: 'pending', accepted: 'accepted' }

  default_scope -> { order(:position) }

  private

  def set_default_position
    self.position ||= self.class.maximum(:position)
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  layout 'hotwire'

  def index
    @pending_ideas = Idea.pending
    @accepted_ideas = Idea.accepted
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(ideas_params)
    @idea.submitter = current_user
    @created_idea = @idea
    @idea = Idea.new if @idea.save

    respond_to :turbo_stream
  end

  def update_multiple
    ActiveRecord::Base.transaction do
      %i[pending accepted].each do |status|
        params["#{status}_ids"].split(',').each.with_index(1) do |id, idx|
          Idea.find(id).update!(position: idx, status: status)
        end
      end
    end
  end

  def ideas_params
    params.require(:idea).permit(:title, :description)
  end
end

app/views/ideas/_idea.html.haml
.bg-white.shadow-md.p-2.mb-2.border.border-gray-500{
  data:{ sortable_target: 'draggable', id: idea.id },
  class: '[&.sortable-ghost.sortable-chosen]:invisible'
}
  %h2.text-xl= idea.title
  %p.text-gray-500= idea.description

app/views/ideas/create.turbo_stream.haml
= turbo_stream.replace('new_idea') { render template: 'ideas/new' }

app/views/ideas/index.html.haml
%h1.text-2xl.text-center Ideas

= form_with url: update_multiple_ideas_path, method: :post, class: 'm-4' do |f|
  %div.flex.gap-4{ class: 'max-w-[90vw] mx-auto' }
    %div{class: "w-1/2 p-3 bg-blue-50"}
      #ideas.mb-4{data:{controller: 'sortable', sortable_group_value: 'ideas', action: 'sort->sortable#sort' }}
        %h2.uppercase.text-center.mb-2.text-sm.text-blue-700 Pending
        = render @pending_ideas
        = f.hidden_field :pending_ids, data: { sortable_target: 'ideaIds' }

      = turbo_frame_tag "new_idea" do
        = link_to 'New idea', new_idea_path, class: 'border border-blue-900 px-2 py-1 rounded mt-2'

    %div{class: "w-1/2 p-3 bg-green-50", data:{controller: 'sortable', sortable_group_value: 'ideas', action: 'sort->sortable#sort' }}
      %h2.uppercase.text-center.mb-2.text-sm.text-green-700 Accepted
      = render @accepted_ideas
      = f.hidden_field :accepted_ids, data: { sortable_target: 'ideaIds' }


= turbo_stream_from 'ideas'

app/views/ideas/new.html.haml
= turbo_frame_tag "new_idea" do
  = form_with(model: @idea, html: { class: 'space-x-2' }) do |f|
    = f.label :title
    = f.text_field :title, class: 'border border-gray-500'
    = f.label :description
    = f.text_field :description, class: 'border border-gray-500'
    = f.submit class: 'border border-blue-900 px-2 py-1 rounded'