config/routes.rb
Rails.application.routes.draw do
  slug = %r{[a-z0-9\-]+/[a-z0-9\-_]+}i

  authenticated :user do
    root to: 'boards#index', as: :authenticated_root
  end

  root to: 'pages#index'

  authenticate :user do
    mount Flipper::UI.app(Flipper), at: '/__flipper__'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resource :user, only: [] do
    resources :features, param: :name, only: %i[destroy] do
      post :create, on: :member
    end
  end

  resources :ideas do
    post :update_multiple, on: :collection
  end

  resources :boards do
    resources :board_tickets, as: :tickets, only: %i[show create] do
      resources :moves, controller: :ticket_moves, only: :create
      resource :labelling, path: 'labels', only: :update
      resource :assignment, path: 'assignees', controller: 'ticket_assignments', only: :update
    end
    get 'tickets/:slug/:number' => 'board_tickets#show', as: :slugged_ticket, constraints: {
      slug: slug
    }
    resources :next_actions, only: :index

    resources :kpis, only: :index
    resource :cumulative_flow, only: :show, controller: 'cumulative_flow'

    # This needs to be last to avoid it intercepting the routes above
    get '*extras' => :show, as: :client_side, on: :member, constraints: { format: :html }
  end

  resources :swimlanes, only: [] do
    resources :tickets, controller: :board_tickets, only: :index
  end

  resources :repos, only: [] do
    resources :labels, only: :index
    resources :assignees, only: :index
  end

  namespace :webhook, only: :create, format: :json do
    resource :github, controller: 'github'
    resource :opsworks
  end

  get '/gh_assets/:slug/*path' => 'github_assets#show', as: :github_asset, constraints: { slug: slug }

  namespace :api do
    resources :boards, only: :show do
      resources :board_tickets, only: %i[index]
      resources :releases, only: :create
    end
  end

  get '/__components__(/*extras)' => 'components#index', as: :components if Rails.env.development?
end

app/controllers/kpis_controller.rb
class KpisController < AuthenticatedController
  load_and_authorize_resource :board

  def index
    authorize! :index, :kpis

    @quarter = derive_quarter_from(params[:date])
    @bug_tickets = BugTicketsCalculator.new(@board, quarter: @quarter)
    @circleci_builds = CircleciBuildsCalculator.new(@board, quarter: @quarter)
    @cycle_time = CycleTimeCalculator.new(
      @board,
      quarter: @quarter,
      start_swimlane_id: cycle_time_params[:start_swimlane_id],
      end_swimlane_id: cycle_time_params[:end_swimlane_id]
    )
  end

  private

  def derive_quarter_from(date)
    return Quarter.current if date.blank?

    Quarter.from(date)
  end

  def cycle_time_params
    params.fetch(:cycle_time, {})
  end
end

app/views/kpis/_bug_tickets.html.haml
%h2.text-xl
  Bugs opened/closed

.text-gray-500.my-5.text-sm
  Bug tickets
  (labelled #{to_or_sentence(BugTicketsCalculator::LABELS) { |label| %["#{label}"] }})
  opened or closed in
  = to_or_sentence(@board.repos) do |repo|
    = link_to(repo.name, repo.html_url,
      target: :_blank, class: 'text-blue-400 hover:text-blue-800')

%table.w-full.text-left.text-sm
  - cell_classes = 'px-3 py-2 border border-gray-300'

  %thead
    - ['Month', 'State', 'Tickets', 'By Month', 'By Quarter'].each do |header|
      %th.bg-gray-50{ class: cell_classes }= header

  %tbody
    - tickets = @bug_tickets.to_a
    - tickets.each.with_index do |stat, index|
      %tr
        - if index.multiple_of?(2)
          %td{ rowspan: 2, class: cell_classes }= stat.date
        %td{ class: "#{cell_classes} #{stat.closed? ? 'bg-green-100' : 'bg-red-100'}" }
          = stat.state
        %td{ class: cell_classes }= stat.count
        - if index.multiple_of?(2)
          - aggregate = stat.count - tickets[index + 1].count # closed - opened
          %td{ rowspan: 2, class: "#{cell_classes} #{aggregate.negative? ? 'bg-red-100' : 'bg-green-100'}" }
            = format '%+d', aggregate
        - if index.zero?
          - aggregate = tickets.partition(&:closed?).map { |stats| stats.sum(&:count) }.inject(&:-)
          %td{ rowspan: 12, class: "#{cell_classes} #{aggregate.negative? ? 'bg-red-100' : 'bg-green-100'}" }
            = format '%+d', aggregate

app/views/kpis/_circleci_builds.html.haml
%h2.text-xl.mt-10
  CircleCI builds

.text-gray-500.my-5.text-sm
  Passing vs. failing CircleCI builds for "build" jobs for
  = to_or_sentence(CircleciBuildsCalculator::BRANCH_NAMES) do |branch|
    %code= branch
  on
  = link_to 'MyRewards', 'https://github.com/CorporateRewards/myrewards', target: :_blank, class: 'text-blue-400 hover:text-blue-800'
  or
  = link_to 'GPS', 'https://github.com/CorporateRewards/redstone', target: :_blank, class: 'text-blue-400 hover:text-blue-800'

%table.w-full.text-left.text-sm
  - cell_classes = 'px-3 py-2 border border-gray-300'

  %thead
    - ['Month', 'Repo', 'State', 'Builds', 'By Repo + Month', 'By Month', 'By Quarter'].each do |header|
      %th.bg-gray-50{ class: cell_classes }= header

  %tbody
    - builds = @circleci_builds.to_a
    - builds.each.with_index do |stat, index|
      %tr
        - if index.multiple_of?(4)
          %td{ rowspan: 4, class: cell_classes }= stat.date
        - if index.multiple_of?(2)
          %td{ rowspan: 2, class: cell_classes }= stat.repo
        %td{ class: "#{cell_classes} #{stat.success? ? 'bg-green-100' : 'bg-red-100'}" }
          = stat.human_state
        %td{ class: cell_classes }= stat.count
        - if index.multiple_of?(2)
          %td{ rowspan: 2, class: cell_classes }
            - total = stat.count + builds[index + 1].count
            #{total} builds (#{calculate_percentage(stat.count, total)} passing)
        - if index.multiple_of?(4)
          %td{ rowspan: 4, class: cell_classes }
            - stats = builds[index..(index + 3)]
            - successes = stats.select(&:success?).sum(&:count)
            - total = stats.sum(&:count)
            #{total} builds (#{calculate_percentage(successes, total)} passing)
        - if index.zero?
          %td{ rowspan: 12, class: cell_classes }
            - successes = builds.select(&:success?).sum(&:count)
            - total = builds.sum(&:count)
            #{total} builds (#{calculate_percentage(successes, total)} passing)

app/views/kpis/_cycle_time.html.haml
%h2.text-xl.mt-10
  Cycle time

= form_for :cycle_time, method: :get, html: { class: 'text-gray-500 my-5 text-sm', id: 'cycle_time_settings' } do |f|
  = hidden_field_tag :date, params[:date]

  Time in business days (Mon-Fri) for tickets to go from
  = f.collection_select :start_swimlane_id, @board.swimlanes, :id, :name, {}, class: 'border border-gray-500 rounded mx-0.5'
  to
  = f.collection_select :end_swimlane_id, @board.swimlanes, :id, :name, {}, class: 'border border-gray-500 rounded mx-0.5'
  in this quarter

%dl.flex.justify-center.-ml-5.pb-7.pt-3.text-sm
  - term_classes = 'px-2 py-1 border border-gray-300 rounded-l ml-7'
  - stat_classes = 'px-3 py-1 border border-gray-300 bg-gray-50 font-bold -ml-px rounded-r'

  %dt{ class: term_classes } Tickets
  %dd{ class: stat_classes }= @cycle_time.results.count

  %dt{ class: term_classes } Mean (average)
  %dd{ class: stat_classes }
    = number_with_precision @cycle_time.mean
    days

  %dt{ class: term_classes } Standard deviation
  %dd{ class: stat_classes }
    = number_with_precision @cycle_time.standard_deviation

  %dt{ class: term_classes } 90th percentile
  %dd{ class: stat_classes }
    = @cycle_time.percentile(90).try(:ceil)
    days


%table.w-full.text-left.text-sm.mb-10
  - cell_classes = 'px-3 py-2 border border-gray-300'

  %thead
    %tr
      - ['Ticket', 'Repo', 'Started at', 'Completed at', 'Cycle time (days)'].each_with_index do |header, index|
        %th.bg-gray-50{ colspan: (2 if index.zero?), class: cell_classes }= header

  %tbody
    - @cycle_time.results.each do |result|
      %tr
        %td{ class: cell_classes }
          = link_to result.number, result.github_url, target: :_blank, class: 'text-blue-500 hover:text-blue-800'
        %td{ class: cell_classes }
          = link_to client_side_board_path(@board, "#{result.slug}/#{result.number}"), class: 'text-blue-500 hover:text-blue-800' do
            = result.title.truncate(100)
        %td{ class: cell_classes }= result.repo_name
        %td{ class: cell_classes }= l result.started_at, format: :short
        %td{ class: cell_classes }= l result.ended_at, format: :short
        %td{ class: cell_classes }= result.duration.ceil

:javascript
  document.querySelector('#cycle_time_settings').addEventListener('change', function(event) {
    event.target.form.submit();
  });

app/views/kpis/index.html.haml
- btn_classes = 'border border-gray-300 px-2 py-1 rounded w-40 hover:border-gray-800 focus:bg-gray-100'

.container.mx-auto.text-center
  .flex.py-4.items-center
    = link_to board_kpis_path(@board, date: @quarter.previous), class: btn_classes do
      Previous quarter

    .flex-1.text-sm.font-bold.uppercase= @quarter.to_s

    - next_quarter = @quarter.next
    - unless next_quarter.future?
      = link_to board_kpis_path(@board, date: next_quarter), class: btn_classes do
        Next quarter

  = render 'bug_tickets'
  = render 'circleci_builds'
  = render 'cycle_time'